markdown:
  url: "https://raw.githubusercontent.com/deltaDAO/pontusx-docs/refs/heads/main/pages/docs/participants-and-federators/ecosystem-participants.mdx"
  key: "Public Address"

redis:
  url: "redis://host.docker.internal:6379"