markdown:
  url: "https://raw.githubusercontent.com/deltaDAO/pontusx-docs/refs/heads/main/pages/docs/participants-and-federators/ecosystem-participants.mdx"
  key: "Public Address"

redis:
  # base_url: "redis://host.docker.internal:6379"
  base_url: ${REDIS_BASE_URL}
  username: ${REDIS_USER}
  password: ${REDIS_PASS}